language: php
services:
  - mysql
php:
- 7.1
node_js:
- 8.11.2
cache:
  yarn: true
  directories:
  - node_modules
  - vendor

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - yarn install

before_install:
  - mysql -e 'CREATE DATABASE gens_test;'

script:
  - vendor/bin/phpunit
  - yarn run production

services:
  - mysql

